services:
  # Backend API service (Flask + AWS Polly)
  - type: web
    name: arabic-bible-tutor-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python aws-polly-server.py
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false  # Set manually in Render dashboard
      - key: AWS_SECRET_ACCESS_KEY
        sync: false  # Set manually in Render dashboard
      - key: AWS_REGION
        value: us-east-1
      - key: FLASK_ENV
        value: production
      - key: PORT
        # Render automatically sets this, no need to specify value
        
  # Static site service (Frontend)  
  - type: static
    name: arabic-bible-tutor-frontend
    buildCommand: echo "No build needed for static HTML/JS"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        headers:
          X-Frame-Options: DENY
          X-Content-Type-Options: nosniff
          Referrer-Policy: strict-origin-when-cross-origin
    envVars:
      - key: API_URL
        # This will be the URL of your Flask service
        # Update this after the Flask service is deployed
        value: https://arabic-bible-tutor-api.onrender.com